<?php
/**
 * @file
 * Main module file for SB form
 */

 /**
 * Implements hook_help().
 */
function sbform_help($path, $arg) {

  if ($path == 'admin/help#sbform') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The sbform module to demonstrate Drupal capacity.') . '</p>';
    return $output;
  }
}

/**
* Implementation of hook_menu().
*/
function sbform_menu() {
  $items['sbform/creditcard'] = array(
      'title' => t('Credit Card'),
      'access arguments' => array('access content'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('sbform_creditcard_form'),
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
  );

  $items['sbform/voucher'] = array(
      'title' => t('Voucher'),
      'access arguments' => array('access content'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('sbform_voucher_form'),
      'access callback' => TRUE,
  );

  return $items;
}

/**
* Credit card form's fields declaration.
*/
function sbform_creditcard_form($form_state) {
    $form = array();

    $form['name']=array(
        '#type'=>'textfield',
        '#title'=>t('Name'),
        '#required'=> TRUE,
      );
    $form['card']=array(
        '#type'=>'textfield',
        '#title'=>t('Card'),
        '#required'=> TRUE,
        '#maxlength' => 16,
      );

     $form['cvv']=array(
        '#type'=>'textfield',
        '#title'=>t('CVV'),
        '#required'=> TRUE,
        '#maxlength' => 4,
      );

     $form['submit']=array(
        '#type'=>'submit',
        '#value'=>t('Submit'),
      );

      return $form;
}
/**
 * Credit card form validation
*/
function sbform_creditcard_form_validate($form, &$form_state) {
}

/**
 * Credit card form submit action
*/
function sbform_creditcard_form_submit($form, &$form_state) {
   drupal_set_message("Credit card has been submitted");
}



/**
* Voucher form's fields declaration.
*/
function sbform_voucher_form($form_state) {
    $form = array();

    $form['name']=array(
        '#type'=>'textfield',
        '#title'=>t('Name'),
        '#required'=> TRUE,
      );
    $form['card']=array(
        '#type'=>'textfield',
        '#title'=>t('Voucher Number'),
        '#required'=> TRUE,
      );
     $form['submit']=array(
        '#type'=>'submit',
        '#value'=>t('Submit'),
      );

      return $form;
}
/**
 * Credit card form validation
*/
function sbform_voucher_form_validate($form, &$form_state) {
}

/**
 * Credit card form submit action
*/
function sbform_voucher_form_submit($form, &$form_state) {
   drupal_set_message("Voucher has been submitted");
}

/**
* Implementation of hook_block_info().
*/
function sbform_block_info(){
	$blocks = array();
	$blocks ['creditcard_block'] = array(
		'info' => t('SB Credit card form block'),
		'status' => TRUE,
		'visibility' => BLOCK_VISIBILITY_LISTED,
		);

	$blocks ['voucher_block'] = array(
		'info' => t('SB Voucher form block'),
		'status' => TRUE,
		'visibility' => BLOCK_VISIBILITY_LISTED,
		);

	return $blocks;
}

function sbform_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  $block = array();
  switch ($delta) {
    case 'creditcard_block':
      // Create your block content here
      $block['subject'] = t('Credit card');
      $block['content'] = drupal_get_form('sbform_creditcard_form');
      break;
    case 'voucher_block':
      // Create your block content here
      $block['subject'] = t('Voucher');
      $block['content'] = drupal_get_form('sbform_voucher_form');
      break;
  }

  return $block;
}



